# Copied and modified from https://github.com/TigerVNC/tigervnc/blob/master/.github/workflows/build.yml
name: Build

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
            repository: "TigerVNC/tigervnc"
            ref: 'v1.14.1'
      - name: Install dependencies
        run: |
          brew install fltk@1.3 pixman ffmpeg
          brew install gnutls nettle gmp
          brew link fltk@1.3
      - name: Configure
        run: cmake -DENABLE_H254=ON -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: make dmg
      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: build/TigerVNC-*.dmg