# Copied and modified from https://github.com/TigerVNC/tigervnc/blob/master/.github/workflows/build.yml
name: Build

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  
# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Checkout tag 
        uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
            repository: "TigerVNC/tigervnc"
            ref: "${{ github.ref_name }}"
      - name: Checkout latest
        uses: actions/checkout@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
            repository: "TigerVNC/tigervnc"
            ref: "master"
      - name: Install dependencies
        run: |
          brew install fltk@1.3 pixman ffmpeg
          brew install gnutls nettle gmp
          brew link fltk@1.3
          env
      - name: Configure
        # run: cmake -G "Unix Makefiles" -DENABLE_H254=ON -DBUILD_SHARED_LIBS=True -DBUILD_STATIC=1 -S . -B build
        run: cmake -G "Unix Makefiles" -DENABLE_H254=ON -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: make dmg
      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: build/TigerVNC-*.dmg
  build-java:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      java_version: '23'
    steps:
      - name: Checkout tag 
        uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
            repository: "TigerVNC/tigervnc"
            ref: "${{ github.ref_name }}"
      - name: Checkout latest
        uses: actions/checkout@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
            repository: "TigerVNC/tigervnc"
            ref: "master"
      - name: Install dependencies
        run: sudo apt install -f ffmpeg
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.java_version }}
      - name: Configure
        working-directory: java
        run: cmake -DENABLE_H254=ON -S . -B build
      - name: Build
        working-directory: java/build
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: java
          path: java/build/VncViewer.jar
  create-release:
    runs-on: ubuntu-latest
    needs: ["build-macos", "build-java"]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4 
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            macOS/TigerVNC-${{ github.ref_name }}.dmg
            java/VncViewer.jar
      